import Head from "next/head";
import type { NextPage } from "next";
import { useSession, signIn, signOut } from "next-auth/react";

import DashTable from "../../components/DashTable";

const DashboardPage: NextPage = () => {
  const handleFetch = async () => {
    const res = await fetch("http://localhost:3000/api/getSubmissions");
    const data = await res.json();
    console.log(data);
  };
  return (
    <>
      <Head>
        <title>HoneyBadger</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {useSession().data?.user ? <Dashboard /> : <NoAuth />}
        <button onClick={handleFetch}>Fetch</button>
      </main>
    </>
  );
};

export default DashboardPage;

const NoAuth: React.FC = () => {
  return (
    <div>
      <p>You are not signed in. You need to sign in to view this page.</p>
      <button onClick={() => signIn("auth0")} className="py-4 text-white">
        Sign In
      </button>
    </div>
  );
};

const Dashboard: React.FC = () => {
  return (
    <>
      <h1 className="text-4xl font-bold text-white">Dashboard</h1>
      <button onClick={() => signOut()} className="py-4 text-white">
        Sign Out
      </button>
      <DashTable />
    </>
  );
};
