import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>HoneyBadger</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-4xl font-bold text-white">HoneyBadger</h1>
        <p className="text-2xl text-white">The Honeybadger app</p>
        {useSession().data?.user ? (
          <>
            <Link href="/dashboard" className="py-4 text-white">
              Go to Dashboard
            </Link>
            <button onClick={() => signOut()} className="py-4 text-white">
              Sign Out
            </button>
          </>
        ) : (
          <button onClick={() => signIn("auth0")} className="py-4 text-white">
            Sign In
          </button>
        )}
      </main>
    </>
  );
};

export default Home;
